export const formStyles = {
  page: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 'calc(100vh - 60px)',
    padding: '2rem 1rem',
    background: 'var(--bg, #f4f5f7)',
  },
  card: {
    background: '#fff',
    borderRadius: 16,
    boxShadow: '0 4px 24px rgba(0,0,0,0.08), 0 1px 4px rgba(0,0,0,0.04)',
    padding: '2.5rem 2rem',
    width: '100%',
    maxWidth: 380,
  },
  header: {
    textAlign: 'center',
    marginBottom: '1.75rem',
  },
  iconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    background: 'rgba(108,99,255,0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 1rem',
  },
  icon: {
    fontSize: '1.3rem',
    color: '#6c63ff',
    fontWeight: 700,
  },
  title: {
    fontSize: '1.4rem',
    fontWeight: 700,
    color: '#111827',
    marginBottom: 4,
    letterSpacing: '-0.02em',
  },
  subtitle: {
    fontSize: '0.875rem',
    color: '#6b7280',
  },
  errorBox: {
    background: '#fff5f5',
    border: '1px solid #fecaca',
    color: '#dc2626',
    borderRadius: 8,
    padding: '0.65rem 0.9rem',
    fontSize: '0.875rem',
    marginBottom: '1rem',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
  },
  label: {
    fontSize: '0.8rem',
    fontWeight: 600,
    color: '#374151',
    letterSpacing: '0.01em',
  },
  input: {
    padding: '0.65rem 0.85rem',
    border: '1.5px solid #e5e7eb',
    borderRadius: 8,
    fontSize: '0.95rem',
    color: '#111827',
    outline: 'none',
    transition: 'border-color 150ms ease',
    background: '#fafafa',
  },
  textarea: {
    padding: '0.65rem 0.85rem',
    border: '1.5px solid #e5e7eb',
    borderRadius: 8,
    fontSize: '0.95rem',
    color: '#111827',
    outline: 'none',
    transition: 'border-color 150ms ease',
    background: '#fafafa',
    resize: 'vertical',
    minHeight: 110,
    fontFamily: 'inherit',
    lineHeight: 1.5,
  },
  btn: {
    marginTop: '0.5rem',
    padding: '0.7rem',
    background: '#1a1a2e',
    color: '#fff',
    border: 'none',
    borderRadius: 9,
    fontSize: '0.95rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'background 150ms ease',
    letterSpacing: '-0.01em',
  },
  switchText: {
    textAlign: 'center',
    marginTop: '1.25rem',
    fontSize: '0.875rem',
    color: '#6b7280',
  },
  switchLink: {
    color: '#6c63ff',
    fontWeight: 600,
    textDecoration: 'none',
  },
  typeCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: '1rem 1.25rem',
    background: '#fafafa',
    border: '1.5px solid #e5e7eb',
    borderRadius: 12,
    cursor: 'pointer',
    transition: 'border-color 150ms ease, background 150ms ease',
    textAlign: 'left',
    width: '100%',
    fontFamily: 'inherit',
    fontSize: '0.95rem',
  },
};
